### ISSUE TITLE
Issue with pyinstaller implementation

### ISSUE THREAD

**Issue by ng1905** [Veil-Framework/Veil-Evasion#363] opened 2016-06-27 22:26 UTC
## Veil-Evasion version
2.27.1

## OS Used - all info (architecture, linux flavor, etc)
Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

## Error you are encountering (include console actions you took prior to error)
*ran ./Veil-Evasion.py as superuser*
> use 34
> set ARCHITECTURE 64
...
 [!] ERROR: Unable to create output file.

> [!] Internal error #2. Unable to generate output. Please run /home/ngs/Veil-Evasion/config/update.py manually

## Expected behavior
Output of payload/python/meterpreter/reverse_tcp as compiled version

## Any additional info you want to tell me
I executed the update.py several times and checked that the recognized install-dir (/usr/share/pyinstaller) is correct. (PyInstaller-Version: 3.2 (compatible with Python2.7))
Maybe I'm doing something wrong but the setup (also executed several times) finished w/o errors (clean install and silent (terminal only)).

**Comment by ChrisTruncer** [comment] 2016-06-27 22:28
x64 architecture won’t work unless using 64 bit wine.  We do not have that
installed, so that would be up to the user to change their wine
architecture and get everything installed accordingly.  This is likely the
reason you’re running into the issue.

If you use a x86 payload, that will work, correct?


-----------------------------------------------------------------------------------------
Christopher Truncer
@christruncer <http://www.twitter.com/christruncer>

On June 27, 2016 at 4:26:08 PM, ng1905 (notifications@github.com) wrote:

Veil-Evasion version

2.27.1
OS Used - all info (architecture, linux flavor, etc)

Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
Error you are encountering (include console actions you took prior to error)

*ran ./Veil-Evasion.py as superuser*

use 34
set ARCHITECTURE 64
...
[!] ERROR: Unable to create output file.

[!] Internal error #2
<https://github.com/Veil-Framework/Veil-Evasion/pull/2>. Unable to generate
output. Please run /home/ngs/Veil-Evasion/config/update.py manually

Expected behavior

Output of payload/python/meterpreter/reverse_tcp as compiled version
Any additional info you want to tell me

I executed the update.py several times and checked that the recognized
install-dir (/usr/share/pyinstaller) is correct. (PyInstaller-Version: 3.2
(compatible with Python2.7))
Maybe I'm doing something wrong but the setup (also executed several times)
finished w/o errors (clean install and silent (terminal only)).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Veil-Framework/Veil-Evasion/issues/363>, or mute the
thread
<https://github.com/notifications/unsubscribe/ABmORkDWGfOFev610Kt-hhOHLo5Ikl77ks5qQE3-gaJpZM4I_kWt>
.

**Comment by ng1905** [comment] 2016-06-27 22:33
First of all, thanks for your FAST(!) reply. Unfortunately, even a x86 payload doesn't work with the same cause... Should I maybe put a full log of setup.py on pastebin?

**Comment by ChrisTruncer** [comment] 2016-06-27 22:37
Yeah, that would definitely be helpful, thanks

**Comment by ng1905** [comment] 2016-06-27 22:47
Here's the log: http://pastebin.com/BTgJMVxz

I'm getting that strange feeling that I'm missing something REALLY obvious.

**Comment by ChrisTruncer** [comment] 2016-06-27 22:59
Have you ran the update.py script manually and then tried generating a payload again?

**Comment by ng1905** [comment] 2016-06-27 23:07
> sudo ./update.py
 [>] Please enter the path of your metasploit installation: /opt/metasploit-framework/

 >Veil-Framework configuration:
>
> [*] OPERATING_SYSTEM = Linux
> [*] TERMINAL_CLEAR = clear
> [*] WINEPREFIX = /home/ngs/.config/wine/veil/
> [*] TEMP_DIR = /tmp/
> [*] MSFVENOM_OPTIONS =
> [*] METASPLOIT_PATH = /opt/metasploit-framework/
> [*] MSFVENOM_PATH = /usr/bin/
> [*] PYINSTALLER_PATH = /usr/share/pyinstaller
>
> [*] VEIL_EVASION_PATH = /home/ngs/Veil-Evasion/
> [*] PAYLOAD_SOURCE_PATH = /usr/share/veil-output/source/
> [*] PAYLOAD_COMPILED_PATH = /usr/share/veil-output/compiled/
> [*] GENERATE_HANDLER_SCRIPT = True
> [*] HANDLER_PATH = /usr/share/veil-output/handlers/
> [*] HASH_LIST = /usr/share/veil-output/hashes.txt
>
> [*] VEIL_CATAPULT_PATH = /home/ngs/Veil-Catapult/
> [*] CATAPULT_RESOURCE_PATH = /usr/share/veil-output/catapult/
>
> Configuration File Written To '/etc/veil/settings.py'

> cd ..
> sudo ./Veil-Evasion.py
> use 34
> set LHOST BLABLA
> set LPORT 4445
> generate
> 1 (PyInstaller)

Same error (x86 Arch)

**Comment by ChrisTruncer** [comment] 2016-06-27 23:50
Can you not run Veil-Evasion as sudo, but as your regular user?

Also, when you can the setup, did you do it as specified?  (sudo ./setup.sh -c)

**Comment by ng1905** [comment] 2016-06-28 04:37
The setup was executed with sudo ./setup.sh -s -c.

When I run Veil as a regular User, I don't even come to the point where the payload should be generated because I'm (obviously) missing the permissions to write in /usr/share.
Maybe I should choose another Output dir?

**Comment by ChrisTruncer** [comment] 2016-06-28 14:47
You should have write permission to the /usr/share/veil-output directory, if not then setup might have been originally run under odd permissions because it should grant that to your account.

**Comment by ChrisTruncer** [comment] 2016-06-28 18:59
Veil isn't using a gui version of Pyinstaller either.

**Comment by ng1905** [comment] 2016-06-28 19:57
I finally got the chance to see a Traceback: http://pastebin.com/gQJ0TmCC

**Comment by ChrisTruncer** [comment] 2016-06-28 20:02
Looks like you are missing a python dependency within wine.  Can you try running the setup with just "sudo ./setup.sh -c"?  And if it asks to clear your existing wine environment please type "y" for yes.

**Comment by ng1905** [comment] 2016-06-28 21:52
I'll try this tomorrow as I'll have to slightly adjust the setup.py to install Veil w/o user interaction or silent arg. (i'm getting stuck on the installation of (wine) python without the silent argument (seems to "display" a window in my emulated X-session)).

**Comment by ChrisTruncer** [comment] 2016-06-28 21:54
So, I needed that information from the beginning.  This cannot be headlessly installed, so this will be the reason you are encountering the error.

I'm going to go ahead and close this out for now since you just gave that information.  If you encounter an issue when not installing headlessly please feel free to open a new issue.

**Closed by ChrisTruncer** 2016-06-28 21:54 UTC
