### ISSUE TITLE
Need help a rare issue .

### ISSUE THREAD

**Issue by LuisAlvarado87** [Veil-Framework/Veil-Evasion#306] opened 2016-04-04 12:14 UTC
## 
when finish the installation:  

[i] If you have any errors running Veil-Evasion, delete your WINE profile (rm -rf ~/.wine/) and re-run: /root/Escritorio/Veil-Evasion/setup/setup.sh

 [i] Done!
 
and run the bash ./Veil-evasion.py i have this : 

in the terminal 

bash ./Veil-EvasioN.py
./Veil-EvasioN.py: línea 10: $'\nFront end launcher for the Veil AV-evasion framework.\n\nHandles command line switches for all options.\nA modules.commoncontroller.Controller() object is instantiated with the\nappropriate switches, or the interactive menu is triggered if no switches\nare provided.\n': no se encontró la orden
^C./Veil-EvasioN.py: línea 14: try:: no se encontró la orden
^C./Veil-EvasioN.py: línea 16: except: no se encontró la orden
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/print line 528.
Error: no such file "========================================================================="
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at /usr/bin/print line 528.
Error: no such file " Necessary component missing"
./Veil-EvasioN.py: línea 19: error sintáctico cerca del elemento inesperado `('
./Veil-EvasioN.py: línea 19: `    print ' Please run: bash %s -s' % os.path.abspath("setup/setup.sh")'

## and have re-install many times de setup.sh ....

**Comment by gordonrs** [comment] 2016-04-04 13:33
Did you install from Kali's repos or did you install from Github? Looks like it might have been from the packages because the new wine environment location should be `/root/.wine/veil/ `in Kali

If from Kali's repos: uninstall it and install from github.

If from github: `sudo ./setup.sh -c` for a clean install

If the problem persists, let us know :)

**Comment by ChrisTruncer** [comment] 2016-04-05 14:27
I'll close this for now, please respond if the problem is still present.

**Closed by ChrisTruncer** 2016-04-05 14:27 UTC

**Comment by LuisAlvarado87** [comment] 2016-04-06 12:14
Good Morning Gordon Robert and Chris Truncer

thanks for the help and sorry for not responding quickly in this
moment I'm reinstalling the veil , and use a program to remove and
reinstall the repositories I found on github I hope serves Called
katoolin

**Comment by LuisAlvarado87** [comment] 2016-04-11 02:36
hello i have try the chmod +x and the veil evasion its 100% fuctionally
 thanks for help !
