### ISSUE TITLE
 session invalid always

### ISSUE THREAD

**Issue by shufan123** [Veil-Framework/Veil-Evasion#238] opened 2015-11-19 22:17 UTC
I am on kali 2.0.
all reverse_http and https for all different languages return a successful  shell but when i issue a command it returns "command not found" and then i get "invalid session id" .
reverse_tcp is flawless
reverse_http and reverse_https if generated by msfvenom work as required.  
Thanks.

**Comment by ChrisTruncer** [comment] 2015-11-22 23:07
Hey there,

I just checked this out myself, and all reverse_http and reverse_https connections are working fine for me.  I also let the connection sit for a while to make sure they would work, and I couldn't get it to error out.

**Comment by void-in** [comment] 2015-11-23 04:58
@shufan123 It would be helpful if you paste the exact commands through which you generated the payload as well as the handler settings. Invalid session ID usually means change in the payload LHOST and handler LHOST settings.

**Comment by shufan123** [comment] 2015-11-23 11:44
@void-in 
`use (whatever the number of the payload is)`
`set LHOST 192.168.1.10`
`set LPORT 500`
`generate`

**Comment by shufan123** [comment] 2015-11-23 11:51
@ChrisTruncer the reverse_powershell with internet explorer UAString module is the only one that works  
i have tried a fresh install of veil dependencies and nothing changed

**Comment by ChrisTruncer** [comment] 2015-11-23 23:04
I just tried this with the python/meterpreter/reverse_http payload and it worked without an issue

**Comment by shufan123** [comment] 2015-11-24 01:07
@ChrisTruncer i have nothing to say or do now but to always use rev_tcp

**Comment by veil-evasion** [comment] 2015-11-24 01:56
I wish I could help you out, but you have to understand if I can't replicate the issue, then I can't really troubleshoot it.

If you're willing to troubleshoot it, I'd be very interested in learning what you find.

**Comment by shufan123** [comment] 2015-11-24 02:25
i am willing but i don't know what to do exactly as the whole point of your project is that nobody can detect the payload's intentions or usage ... i am familiar with with hexrays, binwalk,etc... but if you could tell me what should i do to paste its results here so we could compare i will be grateful

**Comment by shufan123** [comment] 2015-11-24 02:32
I will try wireshark today once i am free

**Comment by b00stfr3ak** [comment] 2015-11-24 23:01
Is your metasploit listener fully up to date?

**Comment by shufan123** [comment] 2015-11-25 02:02
@b00stfr3ak yes it is, i've just updated and before the update i had the same issue

**Comment by shufan123** [comment] 2015-11-25 02:15
where should i upload the pcap file or what should i do with it? as i don't know much about  metasploit's reverse connection method 
@ChrisTruncer @void-in @b00stfr3ak

**Comment by ChrisTruncer** [comment] 2015-11-30 03:48
Seeing as I have been unable to reproduce this at all, I'm going to close it out for now.  But I will leave comments open on this in case you can give any additional insight on reproducing it.  If I am able to do so at a future time, we can open this back up.

**Closed by ChrisTruncer** 2015-11-30 03:48 UTC
